apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1beta1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"name":"standard","namespace":""},"parameters":{"diskformat":"thin"},"provisioner":"kubernetes.io/vsphere-volume"}
      storageclass.beta.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2018-12-18T04:11:01Z"
    name: standard
  parameters:
    diskformat: thin
  provisioner: kubernetes.io/vsphere-volume
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
