apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podaffinity2
  name: podaffinity2
spec:
  containers:
  - name: web
    image: nginx
    resources: {}
#  - name: alpine2
#    image: alpine
#    args:
#    - sleep
#    - "3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            run: podaffinity1
        topologyKey: "kubernetes.io/hostname"
