apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis2
  name: redis2
spec:
  containers:
  - image: redis
    name: redis2
    resources: {}
    volumeMounts:
    - name: testpvc
      mountPath: /data/redis
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: testpvc
    persistentVolumeClaim:
      claimName: task-pv-claim
